---
# Set up Twitter OAuth credentials and add those here.
twitter:
  follow: RunarSogaard
  consumer_key: ~
  consumer_secret: ~
  access_token: ~
  access_token_secret: ~

# Set up a Discord bot and add the token here.
# To get the channel ID where to post tweets, right click on the channel and
# select `Copy ID`. This required developer mode to be active in the Discord
# client.
discord:
  token: ~
  channel_id: 111111111111111111
  tweet_replies: false
  tweet_as_user: true
  embed:
    header: A tweet was posted!
    text: Tweet content
    reply: Replying to
    quote: Quoted
    url: Tweet URL
  plaintext:
    reply_prefix: 'Someone wrote this:'
    reply_postfix: 'So I was like:'
    quote_prefix: 'Look what I saw on Twitter!'
    quote_postfix: 'I''m tottaly like:'
